FROM ubuntu:20.04 AS build
ARG DEBIAN_FRONTEND=noninteractive
MAINTAINER lu.chen.3@stonybrook.edu
RUN apt -y update
RUN apt install -y build-essential libssl-dev cmake libboost-all-dev libgmp-dev libmpfr-dev libeigen3-dev libcgal-dev libcpprest-dev
WORKDIR /usr/src/server/build
COPY server ..
RUN cmake .. && make


FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y libssl-dev libboost-all-dev libgmp-dev libmpfr-dev libeigen3-dev libcgal-dev libcpprest-dev
WORKDIR /usr/src/app
COPY --from=build /usr/src/server/build/generate_cell_ctpop .
COPY requirements.txt .
RUN pip3 install requirements.txt

COPY model model
COPY cell_generation_api.py .

ENV PORT 8000
EXPOSE 8000
CMD [ "python3", "cell_generation_api.py"]